### ISSUE TITLE
How to solve this

### ISSUE THREAD

**Issue by shuvro-zz** [rashidul-hasan/lab-reporting-system#1]
Getting this message while running composer install command.

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Hyn\Framework\FrameworkServiceProvider' not found
```
what is to be done?

**Comment by rashidul-hasan** [comment]
Remove line 173 from `config/app.php`  and run composer install again.

**Comment by shuvro-zz** [comment]
thanks a lot

তথ্যপ্রযুক্তির সবকিছু চাই বাংলায় ।


সোম, ১৩ মে, ২০১৯ তারিখে ৪:০৮ PM টায় এ Rashidul Hasan <
notifications@github.com> লিখেছেন:
