### ISSUE TITLE
sqlstate 42000 syntax error or access violation : 1064

### ISSUE THREAD

**Issue by abiodunbalogun** [rashidul-hasan/lab-reporting-system#2]
I could not migrate my database succesfully: 

sqlstate 42000 syntax error or access violation : 1064

**Comment by rashidul-hasan** [comment]
can you copy the complete error message and post that here? also check if you properly set the database credentials on `.env` file

**Comment by abiodunbalogun** [comment]
Alright bro. I will revert shortly.

**Comment by abiodunbalogun** [comment]
sqlstate 42000 syntax error or access violation : 1064 you have an error in your SQL syntax; also check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, 'remarks.....

The reports table was quoted in the error message.

I also changed the charset and collation to utf8 before running my migration

**Comment by abiodunbalogun** [comment]
I also changed the charset and collation to utf8  in database.php before running my migration

**Comment by rashidul-hasan** [comment]
Looks like the version of MariaDB that you are using doesn't support `json` column type. Can you try upgrading MariaDB? Also to be sure, check all the migration files & comment out the lines where its using a json column type. And then try migrating to see if it works.
